name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.26.0"

      - name: Build app
        run: ./scripts/buildprod.sh

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}

      - name: Set up GCloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Build and push Docker image
        run: gcloud builds submit --tag us-central1-docker.pkg.dev/dulcet-cat-499011-e7/notely-ar-repo/notely:latest .
